spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    #    url: jdbc:h2:./testdb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        check_nullability: true
    defer-datasource-initialization: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

# HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
# Secret 값은 특정 문자열을 Base64 로 인코딩한 값 사용
jwt:
  header: Authorization
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LWlubm92YXRpb25jYW1wLXdlZWs2LWRvaW5nLXRlYW02LWNoYW5oby1zZWNyZXQta2V5
  # 리프레쉬 토큰 유효기간 1시간
  access-token-lifetime-in-seconds: 3600
  # 리프레쉬 토큰 유효기간 3시간
  refresh-token-lifetime-in-seconds: 10800

logging:
  level:
    com.sparta.velog: debug
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
            BasicBinder: trace
